name: Run Trivy vulnerability scanner


on: [ push ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker image for test
        run: |
          docker build -t dim_eccodes_baseimage:test .
      - name: Run Trivy vulnerability scanner on dim_eccodes_baseimage:test
        if: always()
        uses: aquasecurity/trivy-action@0.20.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          image-ref: dim_eccodes_baseimage:test
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
